export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';

export const STATEUSER_SUCCESS = 'STATEUSER_SUCCESS';
export const STATEUSER_FAILURE = 'STATEUSER_FAILURE';

export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET';
export const REQUEST_PASSWORD_RESET_SUCCESS = 'REQUEST_PASSWORD_RESET_SUCCESS';
export const REQUEST_PASSWORD_RESET_FAILURE = 'REQUEST_PASSWORD_RESET_FAILURE';

export const VERIFYING = 'VERIFYING';
export const VERIFICATION_SENT = 'VERIFICATION_SENT';

export const RESETING_PASSWORD = 'RESETING_PASSWORD';
export const RESTORED_PASSWORD_SUCCESS = 'RESTORED_PASSWORD_SUCCESS';
export const RESTORED_PASSWORD_FAILURE = 'RESTORED_PASSWORD_FAILURE';

export const SIGNOUT = 'SIGNOUT';